## Put comments here that give an overall description of what your
## functions do



# control data and timers
x <- matrix(rexp(100), 10)
lt1 <- makeCacheMatrix(x)

start_time <- Sys.time()
lt2 <- cacheSolve(lt1)
sub_time <- Sys.time()
lt2 == solve(x)
end_time <- Sys.time()

sub_time - start_time
end_time - sub_time


## constructor for functions setting and reading the "mother" matrix (x)
## and the inverted matrix (xinv)
## sets the mother matrix (x) from the argument
## returns a list structure of four functions
        
makeCacheMatrix <- function(x = matrix()) {
        xinv <- NULL                       
        set <- function(y) {            
                x <<- y         ## "<<-" operator makes x available to the parent env
                xinv <<- NULL   ## if "<-" is used, the function set doesn't affect the list below
        }
        get <- function() x             
        setinv <- function(inverse) xinv <<- inverse ## again, available to the parent env
        getinv <- function() xinv
        list(set = set, get = get, ## structure to be used as argument for cacheSolve
             setinv = setinv,
             getinv = getinv)
}


## computes or extracts from cache the inverted matrix
## takes the list generated by makeCacheMatrix as argument

cacheSolve <- function(x, ...) {
        xinv <- x$getinv() ## function getinv from the list reports xinv from makeCacheMatrix
        if(!is.null(xinv)) {    ## if the list structure contains non-zero xinv data
                message("getting cached data")
                return(xinv)
        }
        data <- x$get() ## function get from the list reports x from makeCacheMatrix
        xinv <- solve(data, ...) ## computes inverse matrix
        x$setinv(xinv) ## sets to xinv
        xinv
             ## Return a matrix that is the inverse of 'x'
}
