## Put comments here that give an overall description of what your
## functions do



# control data and timers
x <- matrix(rexp(100), 10)
lt1 <- makeCacheMatrix(x)

start_time <- Sys.time()
lt2 <- cacheSolve(lt1)
sub_time <- Sys.time()
lt2 == solve(x)
end_time <- Sys.time()

sub_time - start_time
end_time - sub_time


## constructor for functions setting and reading the "mother" matrix (x)
## and the inverted matrix (xinv)
## returns a list structure of four functions
        
makeCacheMatrix <- function(x = matrix()) {
        xinv <- NULL                       
        set <- function(y) {            
                x <<- y
                xinv <<- NULL
        }
        get <- function() x             
        setinv <- function(inverse) xinv <<- inverse
        getinv <- function() xinv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## computes or extracts from cache the inverted matrix
## takes the list generated by makeCacheMatrix as argument

cacheSolve <- function(x, ...) {
        xinv <- x$getinv()
        if(!is.null(xinv)) {
                message("getting cached data")
                return(xinv)
        }
        data <- x$get()
        xinv <- solve(data, ...)
        x$setinv(xinv)
        xinv
             ## Return a matrix that is the inverse of 'x'
}
